language: node_js
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
node_js:
  - "stable"
branches:
  only:
    - master
after_success:
  - rsync -chavzP --rsh="sshpass -p $FTP_PASSWORD ssh -o StrictHostKeyChecking=no -l $FTP_USER" /* $FTP_USER@ituk.ee:/var/newHub/dev/front